// AUTO-GENERATED by scripts/generate-mud-jsx.mjs — do not edit by hand.
// Bridges MUD's Stencil element types into React's JSX namespace.
// Regenerate with: npm run mud:types
import type * as React from 'react';
import type {} from '@egov-moldova/mud/components';

declare global {
  namespace React {
    namespace JSX {
      interface IntrinsicElements {
      'mud-accordion': React.DetailedHTMLProps<React.HTMLAttributes<HTMLMudAccordionElement>, HTMLMudAccordionElement> &
        Partial<Omit<HTMLMudAccordionElement, keyof HTMLElement>>;
      'mud-accordion-item': React.DetailedHTMLProps<React.HTMLAttributes<HTMLMudAccordionItemElement>, HTMLMudAccordionItemElement> &
        Partial<Omit<HTMLMudAccordionItemElement, keyof HTMLElement>>;
      'mud-avatar': React.DetailedHTMLProps<React.HTMLAttributes<HTMLMudAvatarElement>, HTMLMudAvatarElement> &
        Partial<Omit<HTMLMudAvatarElement, keyof HTMLElement>>;
      'mud-badge': React.DetailedHTMLProps<React.HTMLAttributes<HTMLMudBadgeElement>, HTMLMudBadgeElement> &
        Partial<Omit<HTMLMudBadgeElement, keyof HTMLElement>>;
      'mud-banner': React.DetailedHTMLProps<React.HTMLAttributes<HTMLMudBannerElement>, HTMLMudBannerElement> &
        Partial<Omit<HTMLMudBannerElement, keyof HTMLElement>>;
      'mud-breadcrumb': React.DetailedHTMLProps<React.HTMLAttributes<HTMLMudBreadcrumbElement>, HTMLMudBreadcrumbElement> &
        Partial<Omit<HTMLMudBreadcrumbElement, keyof HTMLElement>>;
      'mud-breadcrumb-item': React.DetailedHTMLProps<React.HTMLAttributes<HTMLMudBreadcrumbItemElement>, HTMLMudBreadcrumbItemElement> &
        Partial<Omit<HTMLMudBreadcrumbItemElement, keyof HTMLElement>>;
      'mud-button': React.DetailedHTMLProps<React.HTMLAttributes<HTMLMudButtonElement>, HTMLMudButtonElement> &
        Partial<Omit<HTMLMudButtonElement, keyof HTMLElement>>;
      'mud-button-group': React.DetailedHTMLProps<React.HTMLAttributes<HTMLMudButtonGroupElement>, HTMLMudButtonGroupElement> &
        Partial<Omit<HTMLMudButtonGroupElement, keyof HTMLElement>>;
      'mud-checkbox': React.DetailedHTMLProps<React.HTMLAttributes<HTMLMudCheckboxElement>, HTMLMudCheckboxElement> &
        Partial<Omit<HTMLMudCheckboxElement, keyof HTMLElement>>;
      'mud-chip': React.DetailedHTMLProps<React.HTMLAttributes<HTMLMudChipElement>, HTMLMudChipElement> &
        Partial<Omit<HTMLMudChipElement, keyof HTMLElement>>;
      'mud-cookie-banner': React.DetailedHTMLProps<React.HTMLAttributes<HTMLMudCookieBannerElement>, HTMLMudCookieBannerElement> &
        Partial<Omit<HTMLMudCookieBannerElement, keyof HTMLElement>>;
      'mud-date-input': React.DetailedHTMLProps<React.HTMLAttributes<HTMLMudDateInputElement>, HTMLMudDateInputElement> &
        Partial<Omit<HTMLMudDateInputElement, keyof HTMLElement>>;
      'mud-date-picker': React.DetailedHTMLProps<React.HTMLAttributes<HTMLMudDatePickerElement>, HTMLMudDatePickerElement> &
        Partial<Omit<HTMLMudDatePickerElement, keyof HTMLElement>>;
      'mud-file-input': React.DetailedHTMLProps<React.HTMLAttributes<HTMLMudFileInputElement>, HTMLMudFileInputElement> &
        Partial<Omit<HTMLMudFileInputElement, keyof HTMLElement>>;
      'mud-file-item': React.DetailedHTMLProps<React.HTMLAttributes<HTMLMudFileItemElement>, HTMLMudFileItemElement> &
        Partial<Omit<HTMLMudFileItemElement, keyof HTMLElement>>;
      'mud-footer': React.DetailedHTMLProps<React.HTMLAttributes<HTMLMudFooterElement>, HTMLMudFooterElement> &
        Partial<Omit<HTMLMudFooterElement, keyof HTMLElement>>;
      'mud-header': React.DetailedHTMLProps<React.HTMLAttributes<HTMLMudHeaderElement>, HTMLMudHeaderElement> &
        Partial<Omit<HTMLMudHeaderElement, keyof HTMLElement>>;
      'mud-header-mega-menu': React.DetailedHTMLProps<React.HTMLAttributes<HTMLMudHeaderMegaMenuElement>, HTMLMudHeaderMegaMenuElement> &
        Partial<Omit<HTMLMudHeaderMegaMenuElement, keyof HTMLElement>>;
      'mud-header-mobile': React.DetailedHTMLProps<React.HTMLAttributes<HTMLMudHeaderMobileElement>, HTMLMudHeaderMobileElement> &
        Partial<Omit<HTMLMudHeaderMobileElement, keyof HTMLElement>>;
      'mud-header-nav-item': React.DetailedHTMLProps<React.HTMLAttributes<HTMLMudHeaderNavItemElement>, HTMLMudHeaderNavItemElement> &
        Partial<Omit<HTMLMudHeaderNavItemElement, keyof HTMLElement>>;
      'mud-header-services-menu': React.DetailedHTMLProps<React.HTMLAttributes<HTMLMudHeaderServicesMenuElement>, HTMLMudHeaderServicesMenuElement> &
        Partial<Omit<HTMLMudHeaderServicesMenuElement, keyof HTMLElement>>;
      'mud-icon': React.DetailedHTMLProps<React.HTMLAttributes<HTMLMudIconElement>, HTMLMudIconElement> &
        Partial<Omit<HTMLMudIconElement, keyof HTMLElement>>;
      'mud-info-box': React.DetailedHTMLProps<React.HTMLAttributes<HTMLMudInfoBoxElement>, HTMLMudInfoBoxElement> &
        Partial<Omit<HTMLMudInfoBoxElement, keyof HTMLElement>>;
      'mud-inline-message': React.DetailedHTMLProps<React.HTMLAttributes<HTMLMudInlineMessageElement>, HTMLMudInlineMessageElement> &
        Partial<Omit<HTMLMudInlineMessageElement, keyof HTMLElement>>;
      'mud-input': React.DetailedHTMLProps<React.HTMLAttributes<HTMLMudInputElement>, HTMLMudInputElement> &
        Partial<Omit<HTMLMudInputElement, keyof HTMLElement>>;
      'mud-input-chip': React.DetailedHTMLProps<React.HTMLAttributes<HTMLMudInputChipElement>, HTMLMudInputChipElement> &
        Partial<Omit<HTMLMudInputChipElement, keyof HTMLElement>>;
      'mud-link': React.DetailedHTMLProps<React.HTMLAttributes<HTMLMudLinkElement>, HTMLMudLinkElement> &
        Partial<Omit<HTMLMudLinkElement, keyof HTMLElement>>;
      'mud-logo': React.DetailedHTMLProps<React.HTMLAttributes<HTMLMudLogoElement>, HTMLMudLogoElement> &
        Partial<Omit<HTMLMudLogoElement, keyof HTMLElement>>;
      'mud-menu': React.DetailedHTMLProps<React.HTMLAttributes<HTMLMudMenuElement>, HTMLMudMenuElement> &
        Partial<Omit<HTMLMudMenuElement, keyof HTMLElement>>;
      'mud-menu-item': React.DetailedHTMLProps<React.HTMLAttributes<HTMLMudMenuItemElement>, HTMLMudMenuItemElement> &
        Partial<Omit<HTMLMudMenuItemElement, keyof HTMLElement>>;
      'mud-modal': React.DetailedHTMLProps<React.HTMLAttributes<HTMLMudModalElement>, HTMLMudModalElement> &
        Partial<Omit<HTMLMudModalElement, keyof HTMLElement>>;
      'mud-notification': React.DetailedHTMLProps<React.HTMLAttributes<HTMLMudNotificationElement>, HTMLMudNotificationElement> &
        Partial<Omit<HTMLMudNotificationElement, keyof HTMLElement>>;
      'mud-numeric-input': React.DetailedHTMLProps<React.HTMLAttributes<HTMLMudNumericInputElement>, HTMLMudNumericInputElement> &
        Partial<Omit<HTMLMudNumericInputElement, keyof HTMLElement>>;
      'mud-pagination': React.DetailedHTMLProps<React.HTMLAttributes<HTMLMudPaginationElement>, HTMLMudPaginationElement> &
        Partial<Omit<HTMLMudPaginationElement, keyof HTMLElement>>;
      'mud-phone-input': React.DetailedHTMLProps<React.HTMLAttributes<HTMLMudPhoneInputElement>, HTMLMudPhoneInputElement> &
        Partial<Omit<HTMLMudPhoneInputElement, keyof HTMLElement>>;
      'mud-progress-tracker': React.DetailedHTMLProps<React.HTMLAttributes<HTMLMudProgressTrackerElement>, HTMLMudProgressTrackerElement> &
        Partial<Omit<HTMLMudProgressTrackerElement, keyof HTMLElement>>;
      'mud-radio': React.DetailedHTMLProps<React.HTMLAttributes<HTMLMudRadioElement>, HTMLMudRadioElement> &
        Partial<Omit<HTMLMudRadioElement, keyof HTMLElement>>;
      'mud-receipt': React.DetailedHTMLProps<React.HTMLAttributes<HTMLMudReceiptElement>, HTMLMudReceiptElement> &
        Partial<Omit<HTMLMudReceiptElement, keyof HTMLElement>>;
      'mud-search-input-circular': React.DetailedHTMLProps<React.HTMLAttributes<HTMLMudSearchInputCircularElement>, HTMLMudSearchInputCircularElement> &
        Partial<Omit<HTMLMudSearchInputCircularElement, keyof HTMLElement>>;
      'mud-search-input-rectangular': React.DetailedHTMLProps<React.HTMLAttributes<HTMLMudSearchInputRectangularElement>, HTMLMudSearchInputRectangularElement> &
        Partial<Omit<HTMLMudSearchInputRectangularElement, keyof HTMLElement>>;
      'mud-segmented-control': React.DetailedHTMLProps<React.HTMLAttributes<HTMLMudSegmentedControlElement>, HTMLMudSegmentedControlElement> &
        Partial<Omit<HTMLMudSegmentedControlElement, keyof HTMLElement>>;
      'mud-select-input': React.DetailedHTMLProps<React.HTMLAttributes<HTMLMudSelectInputElement>, HTMLMudSelectInputElement> &
        Partial<Omit<HTMLMudSelectInputElement, keyof HTMLElement>>;
      'mud-separator': React.DetailedHTMLProps<React.HTMLAttributes<HTMLMudSeparatorElement>, HTMLMudSeparatorElement> &
        Partial<Omit<HTMLMudSeparatorElement, keyof HTMLElement>>;
      'mud-service-button': React.DetailedHTMLProps<React.HTMLAttributes<HTMLMudServiceButtonElement>, HTMLMudServiceButtonElement> &
        Partial<Omit<HTMLMudServiceButtonElement, keyof HTMLElement>>;
      'mud-sidebar': React.DetailedHTMLProps<React.HTMLAttributes<HTMLMudSidebarElement>, HTMLMudSidebarElement> &
        Partial<Omit<HTMLMudSidebarElement, keyof HTMLElement>>;
      'mud-sidebar-group': React.DetailedHTMLProps<React.HTMLAttributes<HTMLMudSidebarGroupElement>, HTMLMudSidebarGroupElement> &
        Partial<Omit<HTMLMudSidebarGroupElement, keyof HTMLElement>>;
      'mud-sidebar-item': React.DetailedHTMLProps<React.HTMLAttributes<HTMLMudSidebarItemElement>, HTMLMudSidebarItemElement> &
        Partial<Omit<HTMLMudSidebarItemElement, keyof HTMLElement>>;
      'mud-spinner': React.DetailedHTMLProps<React.HTMLAttributes<HTMLMudSpinnerElement>, HTMLMudSpinnerElement> &
        Partial<Omit<HTMLMudSpinnerElement, keyof HTMLElement>>;
      'mud-switch': React.DetailedHTMLProps<React.HTMLAttributes<HTMLMudSwitchElement>, HTMLMudSwitchElement> &
        Partial<Omit<HTMLMudSwitchElement, keyof HTMLElement>>;
      'mud-tab': React.DetailedHTMLProps<React.HTMLAttributes<HTMLMudTabElement>, HTMLMudTabElement> &
        Partial<Omit<HTMLMudTabElement, keyof HTMLElement>>;
      'mud-table': React.DetailedHTMLProps<React.HTMLAttributes<HTMLMudTableElement>, HTMLMudTableElement> &
        Partial<Omit<HTMLMudTableElement, keyof HTMLElement>>;
      'mud-tabs': React.DetailedHTMLProps<React.HTMLAttributes<HTMLMudTabsElement>, HTMLMudTabsElement> &
        Partial<Omit<HTMLMudTabsElement, keyof HTMLElement>>;
      'mud-tag': React.DetailedHTMLProps<React.HTMLAttributes<HTMLMudTagElement>, HTMLMudTagElement> &
        Partial<Omit<HTMLMudTagElement, keyof HTMLElement>>;
      'mud-textarea': React.DetailedHTMLProps<React.HTMLAttributes<HTMLMudTextareaElement>, HTMLMudTextareaElement> &
        Partial<Omit<HTMLMudTextareaElement, keyof HTMLElement>>;
      'mud-tooltip': React.DetailedHTMLProps<React.HTMLAttributes<HTMLMudTooltipElement>, HTMLMudTooltipElement> &
        Partial<Omit<HTMLMudTooltipElement, keyof HTMLElement>>;
      }
    }
  }
}

export {};
