/**
 * MUD ships Stencil's own JSX namespace, which React does not read. Without a
 * bridge, every <mud-*> tag is a TS error and you get no prop completion.
 *
 * This reads the tag -> element-interface map out of the published types and
 * emits a React JSX augmentation. Re-run it after bumping @egov-moldova/mud.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

// Resolved by path, not require.resolve: the package's "exports" map does not
// expose dist/types, so subpath resolution would fail.
const typesPath = fileURLToPath(
  new URL('../node_modules/@egov-moldova/mud/dist/types/components.d.ts', import.meta.url),
);
const source = readFileSync(typesPath, 'utf8');

const block = source.match(/interface HTMLElementTagNameMap \{([\s\S]*?)\n {4}\}/);
if (!block) {
  throw new Error('Could not find HTMLElementTagNameMap in @egov-moldova/mud types.');
}

const tags = [...block[1].matchAll(/"(mud-[a-z0-9-]+)":\s*(HTML\w+Element)/g)].map(
  ([, tag, element]) => ({ tag, element }),
);

if (tags.length === 0) throw new Error('No mud-* tags found.');

const lines = tags
  .map(
    ({ tag, element }) =>
      `      '${tag}': React.DetailedHTMLProps<React.HTMLAttributes<${element}>, ${element}> &\n        Partial<Omit<${element}, keyof HTMLElement>>;`,
  )
  .join('\n');

const output = `// AUTO-GENERATED by scripts/generate-mud-jsx.mjs — do not edit by hand.
// Bridges MUD's Stencil element types into React's JSX namespace.
// Regenerate with: npm run mud:types
import type * as React from 'react';
import type {} from '@egov-moldova/mud/components';

declare global {
  namespace React {
    namespace JSX {
      interface IntrinsicElements {
${lines}
      }
    }
  }
}

export {};
`;

writeFileSync(new URL('../src/types/mud-jsx.d.ts', import.meta.url), output);
console.log(`Generated React JSX types for ${tags.length} MUD components.`);
